const state={area:null,events:[],filtered:[],cards:[],map:null,markers:[],circle:null,allDates:false};const $=id=>document.getElementById(id);
const query=()=>new URLSearchParams(location.search);
async function loadIndex(){const d=await (await fetch(`data/areas.json?t=${Date.now()}`)).json();$('areaSelect').innerHTML=d.areas.map(a=>`<option value="${a.id}">${a.displayName}</option>`).join('');await loadArea(query().get('area')||d.areas[0].id)}
async function loadArea(id){const d=await (await fetch(`data/areas/${id}.json?t=${Date.now()}`)).json();state.area=d.area;state.events=d.events||[];$('areaSelect').value=id;$('areaSummary').textContent=`Centro: ${d.area.centreName} · ${d.area.radiusKm} km · prossimi ${d.area.horizonDays} giorni`;$('lastUpdated').textContent=`Ultimo aggiornamento: ${new Date(d.updatedAt).toLocaleString('it-IT')}`;$('dateFilter').options[0].text=`Prossimi ${d.area.horizonDays} giorni`;populateCities(query().get('city'));renderQuickCities();recenter();applyFilters()}
function populateCities(selected){const cities=[...new Set(state.events.map(e=>e.city).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'it'));$('cityFilter').innerHTML='<option value="">Tutte le località</option>'+cities.map(x=>`<option>${x}</option>`).join('');$('cityFilter').value=cities.includes(selected)?selected:''}
function renderQuickCities(){const pref=state.area.id==='ossola'?['Domodossola','Crodo','Formazza']:[];$('quickCities').innerHTML=pref.filter(x=>state.events.some(e=>e.city===x)).map(x=>`<button class="quick-chip" data-city="${x}">${x}</button>`).join('');document.querySelectorAll('.quick-chip').forEach(b=>b.onclick=()=>{$('cityFilter').value=b.dataset.city;applyFilters()})}
function weekend(d){const n=new Date(),s=new Date(n);s.setDate(n.getDate()+(6-n.getDay()+7)%7);s.setHours(0,0,0,0);return d>=s&&d<new Date(+s+172800000)}
function updateUrl(){const p=new URLSearchParams();p.set('area',state.area.id);if($('cityFilter').value)p.set('city',$('cityFilter').value);history.replaceState(null,'',`?${p}`)}
function applyFilters(){const mode=$('dateFilter').value,cat=$('categoryFilter').value,price=$('priceFilter').value,band=$('distanceFilter').value,confidence=$('confidenceFilter').value,view=$('viewFilter').value,city=$('cityFilter').value,q=$('searchInput').value.toLowerCase();state.filtered=state.events.filter(e=>{const d=new Date(e.start),t=`${e.title} ${e.city} ${e.venue} ${e.description}`.toLowerCase();return(!q||t.includes(q))&&(!city||e.city===city)&&(cat==='all'||e.category===cat)&&(price==='all'||(price==='free'?e.free===true:price==='paid'?e.free===false:e.free==null))&&(confidence==='all'||e.confidence===confidence)&&(band==='all'||e.distanceKm<=+band)&&(mode==='all'||mode==='weekend'&&weekend(d)||mode==='evening'&&d.getHours()>=18)&&(view==='recommended'||view==='weekend'&&weekend(d)||view==='food'&&e.category==='food'||view==='music'&&['music','nightlife'].includes(e.category)||view==='sport'&&e.category==='sport'||view==='culture'&&e.category==='culture'||view==='free'&&e.free===true)}).sort((a,b)=>view==='recommended'?b.rankingScore-a.rankingScore:new Date(a.start)-new Date(b.start));state.cards=cards(state.filtered);updateUrl();render();markers()}
function cards(events){if(state.allDates)return events.map(e=>({event:e,sessions:[e]}));const groups=new Map();events.forEach(e=>{const k=e.recurringSeriesId||e.id;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(e)});return [...groups.values()].map(s=>({event:s[0],sessions:s.sort((a,b)=>new Date(a.start)-new Date(b.start))}))}
function render(){const noun=state.cards.length===1?'programma o evento':'programmi o eventi';$('resultCount').textContent=`${state.cards.length} ${noun} · ${state.filtered.length} date`;const grouped=Object.groupBy(state.cards,x=>x.sessions[0].start.slice(0,10));$('eventList').innerHTML=Object.entries(grouped).map(([day,cs])=>`<section class="day-group"><h3 class="day-title">${new Date(day+'T12:00').toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long'})}</h3>${cs.map(card).join('')}</section>`).join('')||'<div class="empty">Nessun evento con questi filtri.</div>';document.querySelectorAll('.event-card').forEach(x=>x.onclick=e=>{if(e.target.matches('.city-chip'))return;select(x.dataset.id)});document.querySelectorAll('.city-chip').forEach(x=>x.onclick=()=>{$('cityFilter').value=x.dataset.city;applyFilters()});document.querySelectorAll('.series-toggle').forEach(x=>x.onclick=e=>{e.stopPropagation();x.closest('.event-card').classList.toggle('expanded')})}
function card(c){const e=c.event,many=c.sessions.length>1;return `<article class="event-card" data-id="${e.id}"><span class="event-time">${new Date(e.start).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</span><span><h3>${many?e.title.replace(/\s+[—-]\s+\d+\s+agosto/i,''):e.title}</h3>${many?`<p class="series-title">${c.sessions.length} prossime date</p>`:''}<p class="event-meta">${e.venue} · <button class="city-chip" data-city="${e.city}">${e.city}</button> · ${e.distanceKm} km</p><span class="tags"><i class="tag">${e.categoryLabel}</i><i class="tag">${e.confidence}</i></span>${many?`<button class="series-toggle">Mostra tutte le date</button><ul class="series-dates">${c.sessions.map(s=>`<li>${new Date(s.start).toLocaleDateString('it-IT',{day:'numeric',month:'short'})} · ${new Date(s.start).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</li>`).join('')}</ul>`:''}</span></article>`}
function select(id){const e=state.events.find(x=>x.id===id);$('contextContent').innerHTML=`<h3>${e.title}</h3><p class="event-meta">${new Date(e.start).toLocaleString('it-IT',{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})}<br>${e.venue}, ${e.city} · ${e.distanceKm} km</p><div class="context-row"><b>Affidabilità</b><br>${e.confidence}</div><div class="context-row">${e.description||'Dettagli sulla fonte originale.'}</div><div class="context-actions"><a class="button" href="${e.sourceUrl}" target="_blank" rel="noreferrer">Fonte originale</a></div>`;const m=state.markers.find(m=>m.eventId===id);if(m){state.map.setView(m.getLatLng(),13);m.openPopup()}}
function init(){state.map=L.map('map').setView([45.554,8.946],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(state.map)}function recenter(){const a=state.area;state.map.setView([a.latitude,a.longitude],10);if(state.circle)state.circle.remove();state.circle=L.circle([a.latitude,a.longitude],{radius:a.radiusKm*1000,color:'#d94c2b',fillOpacity:.04}).addTo(state.map)}function markers(){state.markers.forEach(m=>m.remove());state.markers=state.filtered.map(e=>{const m=L.marker([e.latitude,e.longitude]).addTo(state.map);m.eventId=e.id;m.bindPopup(`<b>${e.title}</b><br>${e.city}`);m.on('click',()=>select(e.id));return m})}
['dateFilter','categoryFilter','priceFilter','distanceFilter','confidenceFilter','viewFilter','cityFilter'].forEach(i=>$(i).onchange=applyFilters);$('searchInput').oninput=applyFilters;$('allDatesToggle').onchange=e=>{state.allDates=e.target.checked;applyFilters()};$('areaSelect').onchange=e=>loadArea(e.target.value);$('refreshButton').onclick=()=>loadArea(state.area.id);init();loadIndex().catch(()=>{$('eventList').innerHTML='<div class="empty">Impossibile caricare gli eventi.</div>'});
