const state={area:null,meta:null,events:[],filtered:[],map:null,markers:[],circle:null,selectedId:null}; const $=id=>document.getElementById(id);
async function loadIndex(){const r=await fetch(`data/areas.json?t=${Date.now()}`);state.meta=await r.json();$('areaSelect').innerHTML=state.meta.areas.map(a=>`<option value="${a.id}">${a.displayName}</option>`).join('');await loadArea(state.meta.areas[0].id)}
async function loadArea(id){const r=await fetch(`data/areas/${id}.json?t=${Date.now()}`),d=await r.json();state.area=d.area;state.events=d.events||[];state.selectedId=null; $('areaSummary').textContent=`Centro: ${d.area.centreName} · ${d.area.radiusKm} km · prossimi ${d.area.horizonDays} giorni · ${d.eventCount} eventi`; $('lastUpdated').textContent=`Ultimo aggiornamento: ${new Date(d.updatedAt).toLocaleString('it-IT')}`; $('dateFilter').options[0].text=`Prossimi ${d.area.horizonDays} giorni`;recenter();applyFilters()}
function weekend(d){const n=new Date(),s=new Date(n);s.setDate(n.getDate()+(6-n.getDay()+7)%7);s.setHours(0,0,0,0);return d>=s&&d<new Date(s.getTime()+172800000)}
function applyFilters(){const mode=$('dateFilter').value,cat=$('categoryFilter').value,price=$('priceFilter').value,band=$('distanceFilter').value,confidence=$('confidenceFilter').value,view=$('viewFilter').value,q=$('searchInput').value.toLowerCase();state.filtered=state.events.filter(e=>{const d=new Date(e.start),text=`${e.title} ${e.city} ${e.description}`.toLowerCase();return (!q||text.includes(q))&&(cat==='all'||e.category===cat)&&(price==='all'||(price==='free'?e.free===true:price==='paid'?e.free===false:e.free==null))&&(confidence==='all'||e.confidence===confidence)&&(band==='all'||e.distanceKm<=+band)&&(mode==='all'||mode==='weekend'&&weekend(d)||mode==='evening'&&d.getHours()>=18)&&(view==='recommended'||view==='weekend'&&weekend(d)||view==='food'&&e.category==='food'||view==='music'&&['music','nightlife'].includes(e.category)||view==='sport'&&e.category==='sport'||view==='culture'&&e.category==='culture'||view==='free'&&e.free===true)}).sort((a,b)=>view==='recommended'?b.rankingScore-a.rankingScore:new Date(a.start)-new Date(b.start));render();markers()}
function render(){ $('resultCount').textContent=`${state.filtered.length} eventi`;const groups=Object.groupBy(state.filtered,e=>e.start.slice(0,10));$('eventList').innerHTML=Object.entries(groups).map(([day,es])=>`<section class="day-group"><h3 class="day-title">${new Date(day+'T12:00').toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long'})}</h3>${es.map(card).join('')}</section>`).join('')||'<div class="empty">Nessun evento con questi filtri.</div>';document.querySelectorAll('.event-card').forEach(x=>x.onclick=()=>select(x.dataset.id))}
function card(e){return `<button class="event-card" data-id="${e.id}"><span class="event-time">${new Date(e.start).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</span><span><h3>${e.title}</h3><p class="event-meta">${e.venue} · ${e.city} · ${e.distanceKm} km</p><span class="tags"><i class="tag">${e.categoryLabel}</i><i class="tag">${e.confidence}</i><i class="tag">${e.free===true?'Gratis':e.free===false?'A pagamento':'Prezzo da verificare'}</i></span></span></button>`}
function select(id){const e=state.events.find(x=>x.id===id);$('contextContent').innerHTML=`<h3>${e.title}</h3><p class="event-meta">${new Date(e.start).toLocaleString('it-IT',{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})}<br>${e.venue}, ${e.city} · ${e.distanceKm} km</p><div class="context-row"><b>Affidabilità</b><br>${e.confidence}</div><div class="context-row">${e.description||'Dettagli sulla fonte originale.'}</div><div class="context-row"><b>Prezzo</b><br>${e.free===true?'Gratis':e.priceText||'Da verificare'}</div><div class="context-actions"><a class="button" href="${e.sourceUrl}" target="_blank" rel="noreferrer">Fonte originale</a></div>`;const m=state.markers.find(m=>m.eventId===id);if(m){state.map.setView(m.getLatLng(),13);m.openPopup()}}
function init(){state.map=L.map('map').setView([45.554,8.946],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(state.map)}
function recenter(){if(!state.map)return;const a=state.area;state.map.setView([a.latitude,a.longitude],a.id==='ossola'?10:10);if(state.circle)state.circle.remove();state.circle=L.circle([a.latitude,a.longitude],{radius:a.radiusKm*1000,color:'#d94c2b',fillOpacity:.04}).addTo(state.map)}
function markers(){state.markers.forEach(m=>m.remove());state.markers=state.filtered.map(e=>{const m=L.marker([e.latitude,e.longitude]).addTo(state.map);m.eventId=e.id;m.bindPopup(`<b>${e.title}</b><br>${e.city} · ${e.distanceKm} km`);m.on('click',()=>select(e.id));return m})}
['dateFilter','categoryFilter','priceFilter','distanceFilter','confidenceFilter','viewFilter'].forEach(i=>$(i).onchange=applyFilters);$('searchInput').oninput=applyFilters;$('areaSelect').onchange=e=>loadArea(e.target.value);$('refreshButton').onclick=()=>loadArea(state.area.id);init();loadIndex().catch(()=>{$('eventList').innerHTML='<div class="empty">Impossibile caricare gli eventi.</div>'});
